version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  test-and-build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: sudo npm i -g pnpm
      - run: sudo pnpm install --no-cache
      - run: sudo pnpm build --no-cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build
      - run: ls
  deploy-to-s3:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          aws-access-key-id: AWS_KEY_ID
          aws-secret-access-key: AWS_KEY_VALUE
          to: 's3://turbo-micro-fe-bucket/remote-app/dist'
          install-aws-cli: true
          from: build/remote-app/dist/
workflows:
  build-and-deploy:
    jobs:
      - test-and-build
      - deploy-to-s3:
          requires:
            - test-and-build