version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.1.1
jobs:
  test-and-build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: sudo npm i -g pnpm
      - run: sudo pnpm install
      - run: sudo pnpm build
  deploy-to-s3:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - aws-s3/copy:
          aws-access-key-id: AWS_KEY_ID
          aws-secret-access-key: AWS_KEY_VALUE
          to: AWS_S3_ID
          install-aws-cli: true 
          from: apps/remote-app/dist/
workflows:
  build-and-deploy:
    jobs:
      - test-and-build
      - deploy-to-s3:
          requires:
            - test-and-build